#ifndef APP_SYSTEMS_H
#define APP_SYSTEMS_H

#include "systems/systems.h"

enum AppSystems {
	SYSTEM_AI = SYSTEM_APP_START,
	SYSTEM_BATTLE,
	SYSTEM_CONSOLE,
	SYSTEM_DISPLAY,
	SYSTEM_FPS_CONTROLLER,
	SYSTEM_INVENTORY,
	SYSTEM_MAINGUI,
	SYSTEM_MAP,
	SYSTEM_MAZE_DRAW,
	SYSTEM_MOVE,
	SYSTEM_ROOM,
};

#endif
